site_name: "Dissonance Voice Chat"
repo_url: "https://github.com/Placeholder-Software/Dissonance"
repo_name: "Issue Tracker"
site_url: https://placeholder-software.co.uk/dissonance/docs/
site_favicon: "dissonance.png"
google_analytics:
    - UA-46722926-2
    - auto
copyright: "<a href='https://placeholder-software.co.uk/'>Placeholder Software</a>"
theme:
    name: material
    include_sidebar: false
    palette:
        scheme: slate
        primary: light blue
    features:
        - navigation.instant
        - toc.integrate
    icon:
        repo: fontawesome/brands/github
    favicon: dissonance.png
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/placeholdersoft
    - icon: fontawesome/brands/discord
      link: https://discord.gg/8dKpP5W
    - icon: fontawesome/brands/github
      link: https://github.com/Placeholder-Software/Dissonance
extra_css:
  - css/pygment_tweaks.css
  - css/header_tweaks.css
use_directory_urls: false
copyright: "<a href='https://placeholder-software.co.uk/dissonance/'>Placeholder Software</a>"
markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.superfences
    - pymdownx.highlight
    - toc:
        permalink: ⚓︎
extra_javascript:
  - javascript/redirector.js
nav:
- Home: "index.md"
- "Project Setup":
    - "Basics/Getting-Started.md"
    - "Basics/Choosing-A-Network.md"
    - "Installation Requirements":
        - "Basics/Licensing.md"
        - "Platforms/Windows Desktop.md"
        - "Platforms/Windows UWP & Hololens.md"
        - "Platforms/Linux.md"
        - "Platforms/MacOS.md"
        - "Platforms/Android.md"
        - "Platforms/iOS.md"
        - "Platforms/Magic Leap.md"
        - "Platforms/Oculus OVR.md"
    - "Basics/Other-Integrations.md"
- "Quick Start Guides":
    - "Mirror Networking": "Basics/Quick-Start-Mirror.md"
    - "Unity Netcode For GameObjects": "Basics/Quick-Start-Unity-NFGO.md"
    - "Forge Networking Remastered": "Basics/Quick-Start-Forge-Remastered.md"
    - "Dark Rift 2": "Basics/Quick-Start-DR2.md"
    - "Photon Unity Networking": "Basics/Quick-Start-Photon.md"
    - "Photon BOLT": "Basics/Quick-Start-Photon-Bolt.md"
    - "TNet3": "Basics/Quick-Start-TNet3.md"
    - "Unity Networking HLAPI": "Basics/Quick-Start-UNet-HLAPI.md"
    - "Steamworks.NET P2P": "Basics/Quick-Start-Steamworks.Net-P2P.md"
    - "WebRTC Network (self contained)": "Basics/Quick-Start-PureP2P.md"
- "Basic Concepts": "Basics/Introduction-To-Chat-Rooms.md"
- "Introductory Tutorials":
    - "Push-To-Talk": "Tutorials/Push-to-Talk.md"
    - "Global Chat Room": "Tutorials/Global-Chat-Room.md"
    - "Team Chat Rooms": "Tutorials/Team-Chat-Rooms.md"
    - "Text Chat": "Tutorials/Text-Chat.md"
    - "Transmit to Player": "Tutorials/Direct-Player-Transmit.md"
    - "Position Tracking": "Tutorials/Position-Tracking.md"
    - "Position Tracking For BOLT": "Tutorials/Position-Tracking-For-Bolt.md"
    - "Proximity Chat": "Tutorials/Proximity-Chat.md"
    - "Collider Chat Rooms": "Tutorials/Collider-Chat-Room.md"
    - "Finding Players": "Tutorials/Player-State.md"
    - "Audio Mixing For Voice": "Tutorials/Audio-Mixing.md"
    - "Access Tokens": "Tutorials/Access-Control-Tokens.md"
    - "Channel Priority": "Tutorials/Channel-Priority.md"
    - "Channel Volume": "Tutorials/Channel-Volume.md"
    - "Custom AudioSource Settings": "Tutorials/Playback-Prefab.md"
    - "Script Controlled Speech": "Tutorials/Script-Controlled-Speech.md"
    - "Spatialization Plugins": "Tutorials/Spatializer-Plugin.md"
- "Advanced Tutorials":
    - "Writing A Custom Network Integration": "Tutorials/Custom-Networking.md"
    - "Writing A Custom IDissonancePlayer": "Tutorials/Custom-Position-Tracking.md"
    - "Writing A Custom Microphone Capture System": "Tutorials/Custom-Microphone-Capture.md"
    - "Direct Access To Recorded Audio": "Tutorials/UsingIMicrophoneSubscriber.md"
    - "Using Channels": "Tutorials/Directly-Using-Channels.md"
    - "Acoustic Echo Cancellation": "Tutorials/Acoustic-Echo-Cancellation.md"
- Reference:
    - Components:
        - "Voice Broadcast Trigger": "Reference/Components/Voice-Broadcast-Trigger.md"
        - "Voice Receipt Trigger": "Reference/Components/Voice-Receipt-Trigger.md"
        - "Dissonance Comms": "Reference/Components/Dissonance-Comms.md"
    - Audio:
        - "Voice Settings": "Reference/Audio/VoiceSettings.md"
        - "IMicrophoneCapture": "Reference/Audio/IMicrophoneCapture.md"
        - "IMicrophoneSubscriber": "Reference/Audio/IMicrophoneSubscriber.md"
    - Networking:
        - "Network Protocol": "Reference/Networking/Network-Protocol.md"
    - Other:
        - "Voice Settings": "Reference/Other/VoiceSettings.md"
        - "Rooms": "Reference/Other/Rooms.md"
        - "RoomChannels": "Reference/Other/RoomChannels.md"
        - "RoomChannel": "Reference/Other/RoomChannel.md"
        - "PlayerChannels": "Reference/Other/PlayerChannels.md"
        - "PlayerChannel": "Reference/Other/PlayerChannel.md"
        - "TextChat": "Reference/Other/TextChat.md"
        - "VoicePlayerState": "Reference/Other/VoicePlayerState.md"
        - "RemoteChannel": "Reference/Other/RemoteChannel.md"